Vagrant.configure(2) do |config|
        config.vm.define "proxy" do |proxy|
            proxy.vm.box = "ubuntu/trusty64"
            proxy.vm.provision "shell", path: "config_proxy.sh"
            proxy.vm.hostname = "valon-server"
			proxy.vm.network "forwarded_port", guest:80, host:8000, auto_correct: true
			proxy.vm.network "private_network", ip: "10.0.0.10"
				proxy.vm.provider "virtualbox" do |vb|
				end
		end
		config.vm.define "web1" do |web1|
			web1.vm.box = "ubuntu/trusty64"
			web1.vm.provision "shell", path: "config_web1.sh"
			web1.vm.hostname = "valon-server-02"
			web1.vm.network "private_network", ip: "10.0.0.11"
				web1.vm.provider "virtualbox" do |vb|
				end
		end
		config.vm.define "web2" do |web2|
			web2.vm.box = "ubuntu/trusty64"
			web2.vm.provision "shell", path: "config_web2.sh"
			web2.vm.hostname = "valon-server-03"
			web2.vm.network "private_network", ip: "10.0.0.12"	
				web2.vm.provider "virtualbox" do |vb|
				end
		end
end
